# This is a basic workflow to help you get started with Actions

name: Automatic updates

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to update to
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch the new release
        run: curl -L https://github.com/seveas/herd/archive/refs/tags/${{ github.event.inputs.tag }}.tar.gz > herd-${{ github.event.inputs.tag }}.tar.gz

      - name: Update the formula
        run: |
          sha256sum=$(sha256sum herd-${{ github.event.inputs.tag }}.tar.gz | cut -f1 -d ' ' )
          sed -e 's![^/]\+.tar.gz!${{ github.event.inputs.tag }}.tar.gz!' -i herd.rb
          sed -e "s!sha256 \".*\"!sha256 \"$sha256sum\"!" -i herd.rb

      - name: File pull request
        run: |
         git diff --quiet || {
            git config --global user.email dennis@kaarsemaker.net
            git config --global user.name "Dennis Kaarsemaker"
            git checkout -b new-release-${{ github.event.inputs.tag }}
            git commit -am "Automated update to ${{ github.event.inputs.tag }}"
            git push -f origin new-release-${{ github.event.inputs.tag }}
            gh pr create --title "Automated update to ${{ github.event.inputs.tag }}" --body "Automated update to ${{ github.event.inputs.tag }}"
         }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
